### ISSUE TITLE
filtering too slow.

### ISSUE THREAD

**Issue by jinhyunglee** [paninski-lab/yass#111] opened 2018-02-13 20:12 UTC
it is because of loading one channel at a time using mmap.
One suggestion might be

Assuming that loading one channel at a time is not slow if the data is saved in wide format,
if the data is given as long, transpose it and save it as wide and proceed?

**Comment by edublancas** [comment] 2018-02-13 20:16
@calvinytong we can use your help here a lot, we need to evaluate what's the problem with the filtering part. I am working on refactoring the processor so if you can helps us with this would be amazing

**Comment by calvinytong** [comment] 2018-02-13 22:54
Could you clarify what you mean by wide and long format? Also how are we sure that it is because it is because we are loading channel by channel?

**Comment by jinhyunglee** [comment] 2018-02-13 23:02
Currently in the code,
https://github.com/paninski-lab/yass/blob/master/src/yass/batch/batch.py#L399,
line 399 runs fast but line 401 to 404 is extremely slow.

However, if I put something like 
subset = np.copy(subset) ( or subset = subset.astype('float32') )
in between 399 and 401,
everything else becomes faster except the code that I added in.

long and wide are how we saved binary file.
If there are C channels and T timebins,
by Eduardo's definition,
long is saving recording with shape [T, C] as a binary file.
and wide is saving recording with shape [C,T].
Hope this is clear.

**Comment by calvinytong** [comment] 2018-02-15 16:51
Yes it is clear thank you. For the future, I would recommend posting the first bit of that explanation (not the part where you explain Eduardo's definition) in the original description of the issue. Issues should be as descriptive as possible, and if you know the origin of the bug you should state it.

**Comment by calvinytong** [comment] 2018-02-17 03:43
Any update on profiling the code? (I don't have the large datasets so I can't really run and check)

**Comment by edublancas** [comment] 2018-02-17 18:14
@calvinytong please talk to @jinhyunglee or @catubc on getting the large datasets for profiling

**Comment by calvinytong** [comment] 2018-02-20 17:42
Update on this: @jinhyunglee and I talked about it. It seems we are using the memory map incorrectly (happy to give more details via dm). We are going to reading directly from disk.

**Comment by edublancas** [comment] 2018-02-20 19:52
Yes, we know that the issue is the memory map. We need to implement a simple class that does the `big_file[:100, :3]` thing from a binary file. Do you want to work on that @calvinytong ?

Then we will replace memory map for that.

**Comment by edublancas** [comment] 2018-03-19 20:50
This was fixed by changing to mult-channel operations, right? can we close this @jinhyunglee ?

**Closed** 2018-05-24 17:33 UTC
Labels: critical, enhancement
